sudo: false

language: node_js

node_js:
  - "7"

os:
  - linux
  - macosx
  - windows

matrix:
  include:
  - node_js: 6
    os: linux
  - node_js: 4
    os: linux

cache:
  yarn: true
  directories:
    - node_modules

script: grunt

notifications:
  irc:
    channels:
    - "irc.hackint.org#freifunkR"
    - "irc.hackint.org#meshviewer"
    nick: ci
    use_notice: true
