sudo: false

language: node_js

node_js:
  - "7"
  - "6"
  - "4"

os:
  - linux
  - macosx
  - windows

cache:
  yarn: true
  directories:
    - node_modules
    - bower_components

script: grunt

notifications:
  irc:
    channels: "irc.hackint.org#freifunkR"
    channels: "irc.hackint.org#meshviewer"
    nick: ci
    use_notice: true
