sudo: false

language: node_js

node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.11"
  - "iojs"

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - npm install -g grunt-cli

install:
  - npm install

script: grunt

notifications:
  irc:
    channels: "irc.hackint.org#freifunkR"
    nick: ci
    use_notice: true
